import mongoose from "mongoose";

const resumeSchema = new mongoose.Schema({
  // 1. Links the resume to the actual logged-in user
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  
  // 2. The unique string ID generated by your React frontend 
  // (Prevents duplicate saves when updating an existing resume)
  frontendId: {
    type: String,
    required: true
  },

  // 3. The name of the resume for the Dashboard (e.g., "Google Software Engineer App")
  resumeTitle: {
    type: String,
    default: 'Untitled Resume'
  },
  
  // 4. The entire React state (education, workExp, skills, etc.) 
  // gets saved seamlessly inside this single object!
  resumeData: {
    type: Object,
    required: true
  }

}, { timestamps: true });

const ResumeMakerModel = mongoose.model("ResumeMaker", resumeSchema);
export default ResumeMakerModel;